name: Download and Extract APK

on:
  workflow_dispatch:
    inputs:
      apks_url:
        description: 'Direct URL to the .apkm file'
        required: true
        type: string

jobs:
  extract-universal-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Azul Zulu JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Download bundletool
        run: |
          curl -L -o bundletool.jar https://github.com/google/bundletool/releases/download/1.15.6/bundletool-all-1.15.6.jar

      - name: Download .apkm file
        run: |
          mkdir app
          curl -L "${{ github.event.inputs.apks_url }}" -o app/app.aab

      - name: Build unsigned universal APK
        run: |
          java -jar bundletool.jar build-apks \
            --bundle=app/app.aab \
            --output=output.apks \
            --mode=universal \
            --overwrite

      - name: Extract APK
        run: |
          unzip output.apks -d output_apks
          ls output_apks

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: universal-apk
          path: output_apks/universal.apk